select TITLE, NAME
from MOVIE JOIN MOVIEEXEC ON PRODUCERC#=CERT#
WHERE MOVIEEXEC.NAME = (
	SELECT NAME 
	FROM MOVIE JOIN MOVIEEXEC ON MOVIE.PRODUCERC# = MOVIEEXEC.CERT# 
	WHERE TITLE LIKE 'Star Wars'
)

SELECT DISTINCT MOVIEEXEC.NAME FROM MOVIE JOIN MOVIEEXEC ON MOVIE.PRODUCERC#=MOVIEEXEC.CERT# WHERE TITLE IN (
	SELECT MOVIETITLE 
	FROM STARSIN 
	WHERE STARNAME LIKE 'Harrison Ford'
)

SELECT DISTINCT STUDIONAME AS name, STARNAME
FROM STARSIN JOIN MOVIE ON STARSIN.MOVIETITLE LIKE MOVIE.TITLE
ORDER BY STUDIONAME

SELECT STARNAME, NETWORTH, TITLE
FROM (STARSIN JOIN MOVIE ON STARSIN.MOVIETITLE LIKE MOVIE.TITLE) JOIN MOVIEEXEC ON MOVIE.PRODUCERC#=MOVIEEXEC.CERT#
WHERE NETWORTH >= ALL (
	SELECT NETWORTH FROM MOVIEEXEC
)

SELECT NAME, MOVIETITLE FROM MOVIESTAR LEFT JOIN STARSIN ON NAME LIKE STARNAME WHERE MOVIETITLE IS NULL
