SELECT * 
FROM SHIPS JOIN CLASSES ON SHIPS.CLASS LIKE CLASSES.CLASS
ORDER BY SHIPS.NAME

SELECT *
FROM SHIPS RIGHT JOIN CLASSES ON SHIPS.CLASS LIKE CLASSES.CLASS
WHERE SHIPS.NAME IS NOT NULL OR CLASSES.CLASS IN (SELECT NAME FROM SHIPS)
ORDER BY SHIPS.NAME

SELECT CLASSES.COUNTRY, SHIPS.NAME 
FROM (SHIPS LEFT JOIN OUTCOMES ON SHIPS.NAME LIKE OUTCOMES.SHIP) JOIN CLASSES ON SHIPS.CLASS LIKE CLASSES.CLASS
WHERE OUTCOMES.BATTLE IS NULL
ORDER BY COUNTRY

SELECT SHIPS.NAME AS 'Ship Name'
FROM SHIPS JOIN CLASSES ON SHIPS.CLASS LIKE CLASSES.CLASS
WHERE LAUNCHED=1916 AND NUMGUNS >= 7

SELECT OUTCOMES.SHIP, OUTCOMES.BATTLE, BATTLES.DATE
FROM OUTCOMES JOIN BATTLES ON OUTCOMES.BATTLE LIKE BATTLES.NAME
WHERE OUTCOMES.RESULT LIKE 'sunk'
ORDER BY BATTLES.NAME

SELECT SHIPS.NAME, CLASSES.DISPLACEMENT, SHIPS.LAUNCHED
FROM SHIPS JOIN CLASSES ON SHIPS.CLASS LIKE CLASSES.CLASS
WHERE SHIPS.NAME LIKE SHIPS.CLASS

SELECT *
FROM CLASSES 
WHERE CLASSES.CLASS NOT IN (
	SELECT CLASS FROM SHIPS
)

SELECT SHIPS.NAME, CLASSES.DISPLACEMENT, CLASSES.NUMGUNS, OUTCOMES.RESULT
FROM (SHIPS JOIN CLASSES ON SHIPS.CLASS LIKE CLASSES.CLASS) JOIN OUTCOMES ON SHIPS.NAME LIKE OUTCOMES.SHIP
WHERE OUTCOMES.BATTLE LIKE 'North Atlantic'

