SELECT COUNT(CLASS) AS '№_Classes'
FROM CLASSES
WHERE TYPE LIKE 'bb'

SELECT CLASS, AVG(NUMGUNS)
FROM CLASSES
WHERE TYPE LIKE 'bb'
GROUP BY CLASS

SELECT AVG(NUMGUNS) AS avgGuns
FROM CLASSES
WHERE TYPE LIKE 'bb'

SELECT class, MIN(LAUNCHED) AS FirstYear, MAX(LAUNCHED) as LastYear
FROM SHIPS
GROUP BY CLASS

SELECT class, COUNT(*) AS '№_Sunk'
FROM SHIPS JOIN OUTCOMES ON SHIPS.NAME LIKE OUTCOMES.SHIP 
WHERE OUTCOMES.RESULT LIKE 'sunk'
GROUP BY SHIPS.CLASS

SELECT class, COUNT(*) AS '№_Sunk'
FROM SHIPS JOIN OUTCOMES ON SHIPS.NAME LIKE OUTCOMES.SHIP 
WHERE OUTCOMES.RESULT LIKE 'sunk' AND SHIPS.CLASS IN (
	SELECT CLASS FROM SHIPS GROUP BY CLASS HAVING COUNT(*) > 2
)
GROUP BY SHIPS.CLASS

SELECT COUNTRY AS country, AVG(BORE) AS avg_bore
FROM CLASSES
WHERE CLASSES.TYPE LIKE 'bb'
GROUP BY COUNTRY
