SELECT DISTINCT COUNTRY FROM CLASSES
WHERE NUMGUNS >= ALL(SELECT DISTINCT NUMGUNS FROM CLASSES)

SELECT DISTINCT CLASS FROM SHIPS, (SELECT SHIP FROM OUTCOMES WHERE RESULT LIKE 'sunk') DAMAGED_SHIPS 
WHERE SHIPS.NAME = DAMAGED_SHIPS.SHIP

SELECT NAME, CLASS FROM SHIPS WHERE CLASS IN (SELECT CLASS FROM CLASSES WHERE BORE = 16)

SELECT BATTLE FROM OUTCOMES WHERE SHIP IN (SELECT NAME FROM SHIPS WHERE CLASS LIKE 'Kongo')

SELECT CLASS, NAME 
FROM SHIPS 
WHERE CLASS IN 
	(SELECT CLASS 
	FROM CLASSES C 
	WHERE NUMGUNS >= ALL(
		SELECT NUMGUNS 
		FROM CLASSES 
		WHERE BORE = C.BORE))
ORDER BY CLASS