SELECT * FROM product
SELECT * FROM PC

SELECT DISTINCT MAKER
FROM product P, 
	(SELECT MODEL FROM PC
	WHERE speed > 500) M
WHERE P.model = M.model

SELECT CODE, model, price FROM printer
WHERE printer.price >= ALL(SELECT price FROM printer)

SELECT * FROM laptop
WHERE laptop.speed < ALL(SELECT speed FROM PC)

SELECT * FROM 
(SELECT MODEL, PRICE FROM printer
UNION 
SELECT MODEL, PRICE FROM PC
UNION
SELECT MODEL, PRICE FROM laptop
) RES
WHERE RES.price >= ALL(SELECT DISTINCT LAMBDA.price FROM (
SELECT PRICE FROM printer
UNION 
SELECT PRICE FROM PC
UNION
SELECT PRICE FROM laptop) LAMBDA)

SELECT DISTINCT MAKER 
FROM product 
WHERE type LIKE 'Printer' 
AND product.model IN 
(SELECT MODEL FROM PRINTER 
WHERE PRICE <= ALL
(SELECT DISTINCT PRICE FROM
(SELECT * FROM PRINTER WHERE color LIKE 'y') 
COLOR_PRINTERS) AND color LIKE 'y')

SELECT MAKER 
FROM product
WHERE type LIKE 'PC'
AND product.model IN
(SELECT MODEL FROM 
	(SELECT * FROM 
		(SELECT * FROM pc 
		WHERE ram <= ALL (SELECT ram FROM pc)) LOWEST_RAM 
	WHERE speed >= 
	ALL(SELECT speed FROM pc 
		WHERE ram <= ALL (SELECT ram FROM pc))) RES)


