select * from SHIPS
select * from classes
SELECT * FROM OUTCOMES
SELECT * FROM BATTLES

select SHIPS.NAME
from SHIPS, CLASSES
where SHIPS.CLASS = CLASSES.CLASS AND 
CLASSES.DISPLACEMENT >= 50000

SELECT SHIPS.NAME, CLASSES.DISPLACEMENT, CLASSES.NUMGUNS
FROM 
	OUTCOMES, 
	SHIPS,
	CLASSES
WHERE 
	OUTCOMES.BATTLE LIKE '%Guadalcanal%' AND
	OUTCOMES.SHIP = SHIPS.NAME AND 
	SHIPS.CLASS = CLASSES.CLASS

select COUNTRY
from 
	CLASSES
WHERE TYPE IN ('bb', 'bc') 
GROUP BY COUNTRY
HAVING COUNT(DISTINCT TYPE) >= 2;

/* 2nd Way
(select COUNTRY
from CLASSES
where TYPE LIKE 'bb')
INTERSECT
(select COUNTRY
from CLASSES
WHERE TYPE LIKE 'bc')
*/

(SELECT SHIP
FROM OUTCOMES
WHERE RESULT LIKE 'damaged')
INTERSECT
(SELECT SHIP
FROM OUTCOMES
GROUP BY SHIP
HAVING COUNT(DISTINCT RESULT) >= 2)




