SELECT DISTINCT SHIP 
FROM OUTCOMES 
WHERE SHIP LIKE 'C%' OR SHIP LIKE 'K%'

SELECT * FROM OUTCOMES
select * from ships
SELECT SHIPS.NAME, CLASSES.COUNTRY 
FROM SHIPS JOIN CLASSES ON SHIPS.CLASS LIKE CLASSES.CLASS
WHERE NAME NOT IN(
	SELECT SHIP FROM OUTCOMES WHERE RESULT LIKE 'sunk'
)
ORDER BY NAME

SELECT CLASSES.COUNTRY, COUNT(SHIPS.NAME) AS num_sunk_ships
FROM (SHIPS JOIN 
		OUTCOMES ON SHIPS.NAME LIKE OUTCOMES.SHIP) RIGHT JOIN 
		CLASSES ON SHIPS.CLASS LIKE CLASSES.CLASS AND OUTCOMES.RESULT LIKE 'sunk'
GROUP BY CLASSES.COUNTRY

SELECT BATTLE
FROM OUTCOMES
GROUP BY BATTLE
HAVING COUNT(*) > (SELECT COUNT(*) FROM OUTCOMES WHERE BATTLE LIKE 'Guadalcanal' GROUP BY BATTLE)

SELECT BATTLE
FROM OUTCOMES
GROUP BY BATTLE
HAVING COUNT(*) > (SELECT COUNT(*) FROM OUTCOMES WHERE BATTLE LIKE 'Surigao Strait' GROUP BY BATTLE)

SELECT NAME, CLASSES.DISPLACEMENT, CLASSES.NUMGUNS
FROM SHIPS JOIN CLASSES ON SHIPS.CLASS LIKE CLASSES.CLASS
WHERE SHIPS.CLASS IN (
	SELECT CLASS
	FROM (
		SELECT * 
			FROM CLASSES 
			WHERE DISPLACEMENT <= ALL(
				SELECT DISTINCT DISPLACEMENT 
				FROM CLASSES
			)
		) RES
	WHERE RES.NUMGUNS >= ALL(
		SELECT DISTINCT NUMGUNS 
		FROM CLASSES 
		WHERE DISPLACEMENT <= ALL(
			SELECT DISTINCT DISPLACEMENT 
			FROM CLASSES
		)
	)
)

SELECT COUNT(*) AS num_ships
FROM (SELECT *
		FROM OUTCOMES JOIN BATTLES ON OUTCOMES.BATTLE LIKE BATTLES.NAME 
		WHERE RESULT LIKE 'damaged') 
	RES1 JOIN
	(SELECT *
		FROM OUTCOMES JOIN BATTLES ON OUTCOMES.BATTLE LIKE BATTLES.NAME 
		WHERE RESULT LIKE 'ok') 
	RES2 ON RES1.SHIP LIKE RES2.SHIP
WHERE RES1.DATE < RES2.DATE

SELECT RES1.SHIP AS ship_name
FROM (SELECT *
		FROM OUTCOMES JOIN BATTLES ON OUTCOMES.BATTLE LIKE BATTLES.NAME 
		WHERE RESULT LIKE 'damaged') 
	RES1 JOIN
	(SELECT *
		FROM OUTCOMES JOIN BATTLES ON OUTCOMES.BATTLE LIKE BATTLES.NAME 
		WHERE RESULT LIKE 'ok') 
	RES2 ON RES1.SHIP LIKE RES2.SHIP
WHERE RES1.DATE < RES2.DATE AND (
	SELECT COUNT(*) 
	FROM OUTCOMES 
	WHERE BATTLE LIKE RES1.BATTLE 
	GROUP BY OUTCOMES.BATTLE) <
	(SELECT COUNT(*) 
	FROM OUTCOMES 
	WHERE BATTLE LIKE RES2.BATTLE 
	GROUP BY OUTCOMES.BATTLE)




