SELECT TITLE, YEAR, LENGTH 
FROM MOVIE
WHERE (YEAR IS NULL OR YEAR < 2000) AND (LENGTH IS NULL OR LENGTH > 120)

SELECT name, gender FROM MOVIESTAR
WHERE NAME LIKE 'J%' AND year(BIRTHDATE) > 1948
ORDER BY NAME DESC

SELECT MOVIE.STUDIONAME, COUNT(DISTINCT STARNAME) AS 'num_actors'
FROM STARSIN JOIN MOVIE ON STARSIN.MOVIETITLE LIKE MOVIE.TITLE
GROUP BY MOVIE.STUDIONAME

SELECT MOVIESTAR.NAME, COUNT(STARSIN.MOVIETITLE) AS 'num_movies'
FROM STARSIN RIGHT JOIN MOVIESTAR ON STARSIN.STARNAME LIKE MOVIESTAR.NAME
GROUP BY MOVIESTAR.NAME

SELECT STUDIONAME, TITLE, YEAR
FROM MOVIE M
WHERE YEAR >= ALL(SELECT YEAR FROM MOVIE WHERE STUDIONAME LIKE M.STUDIONAME)
ORDER BY STUDIONAME DESC

SELECT NAME FROM MOVIESTAR
WHERE GENDER LIKE 'M' AND BIRTHDATE >= ALL(
	SELECT BIRTHDATE FROM MOVIESTAR WHERE GENDER LIKE 'M'
)

SELECT STUDIONAME, STARNAME, COUNT(*) AS 'num_movies'
FROM STARSIN SI JOIN MOVIE M ON SI.MOVIETITLE LIKE M.TITLE
GROUP BY STUDIONAME, STARNAME
HAVING COUNT(*) >= ALL(
	SELECT COUNT(*) 
	FROM STARSIN JOIN MOVIE ON STARSIN.MOVIETITLE LIKE MOVIE.TITLE 
	WHERE M.STUDIONAME LIKE STUDIONAME 
	GROUP BY STUDIONAME, STARNAME
)

SELECT STARSIN.MOVIETITLE, STARSIN.MOVIEYEAR, COUNT(STARNAME) AS num_actors
FROM STARSIN
GROUP BY MOVIETITLE, MOVIEYEAR
HAVING COUNT(STARNAME) > 2


