USE Flights
CREATE TABLE AIRLINE (
	CODE VARCHAR(100) CONSTRAINT pk_airline PRIMARY KEY,
	NAME VARCHAR(100) CONSTRAINT uk_airline_name UNIQUE,
	COUNTRY VARCHAR(100)
);

CREATE TABLE AGENCY (
	NAME VARCHAR(100),
	COUNTRY VARCHAR(100) NOT NULL,
	CITY VARCHAR(50),
	PHONE VARCHAR(50)
	CONSTRAINT pk_agency PRIMARY KEY(NAME)
);

CREATE TABLE AIRPLANE (
	CODE VARCHAR(100) CONSTRAINT pk_airplane PRIMARY KEY,
	TYPE VARCHAR(50) NOT NULL,
	SEATS INT NOT NULL CONSTRAINT seats CHECK (SEATS > 0),
	YEAR SMALLINT
);

CREATE TABLE CUSTOMER (
	ID INT CONSTRAINT pk_customer PRIMARY KEY,
	FNAME VARCHAR(30) NOT NULL,
	LNAME VARCHAR(30) NOT NULL,
	EMAIL VARCHAR(100) CHECK (CHARINDEX('.', EMAIL) > 1 AND CHARINDEX('@', EMAIL) > 1 AND LEN(EMAIL) >= 6)
);

CREATE TABLE AIRPORT (
	CODE VARCHAR(100) CONSTRAINT pk_airport PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	COUNTRY VARCHAR(100) NOT NULL,
	CITY VARCHAR(100) NOT NULL
	CONSTRAINT uk_airport UNIQUE(NAME, COUNTRY)
);

CREATE TABLE FLIGHT (
	FNUMBER VARCHAR(100) ,
	AIRLINE_OPERATOR VARCHAR(100) CONSTRAINT fk_flight_airline_operator REFERENCES AIRLINE(CODE),
	DEP_AIRPORT VARCHAR(100) CONSTRAINT fk_flight_dep_airport REFERENCES AIRPORT(CODE),
	ARR_AIRPORT VARCHAR(100) CONSTRAINT fk_flight_arr_airport REFERENCES AIRPORT(CODE),
	FLIGHT_TIME DATETIME,
	FLIGHT_DURATION INT,
	AIRPLANE VARCHAR(100) CONSTRAINT fk_flight_airplane REFERENCES AIRPLANE(CODE),
	CONSTRAINT pk_flight PRIMARY KEY(FNUMBER, AIRLINE_OPERATOR)
);

CREATE TABLE BOOKING (
	CODE VARCHAR(100) CONSTRAINT pk_booking PRIMARY KEY,
	AGENCY VARCHAR(100) CONSTRAINT fk_booking_agency REFERENCES AGENCY(NAME),
	AIRLINE_CODE VARCHAR(100),
	FLIGHT_NUMBER VARCHAR(100),
	CUSTOMER_ID INT CONSTRAINT fk_booking_customer_id REFERENCES CUSTOMER(ID),
	BOOKING_DATE DATETIME,
	FLIGHT_DATE DATETIME,
	PRICE DECIMAL(10,2),
	STATUS bit DEFAULT 0, 
	CONSTRAINT fk_booking_flight FOREIGN KEY (FLIGHT_NUMBER, AIRLINE_CODE)
	REFERENCES FLIGHT(FNUMBER, AIRLINE_OPERATOR),
	CONSTRAINT BOOKING_DATE_FLIGHT_DATE CHECK (BOOKING_DATE <= FLIGHT_DATE)
);

SELECT * FROM BOOKING
ALTER TABLE BOOKING DROP CONSTRAINT BOOKING_DATE_FLIGHT_DATE
SELECT * FROM BOOKING
ALTER TABLE BOOKING ADD CONSTRAINT BOOKING_DATE_FLIGHT_DATE CHECK (BOOKING_DATE <= FLIGHT_DATE)
SELECT * FROM BOOKING
--ERROR - INSERT INTO BOOKING VALUES(5, 'A', 3, 2, 3, '2000-10-20', '2000-10-20', 12412.22, DEFAULT)